### PR TITLE
Added nav-bar, more readable CSS, and Bootstrap.

### PR DESCRIPTION
**Pull request by shahzeb1**
Cleaned up the website. Refer to issue https://github.com/studenton/shuffle/issues/5.

### CODE REVIEW

**Comment by shahzeb1** [comment]
Also added an "About" button which pops up a modal with some information.

**Comment by shahzeb1** [comment]
I have also gone ahead and added social meta tags for Facebook and Twitter. https://github.com/studenton/shuffle/issues/4

Please replace the values in the last two tags with images.

**Comment by amitness** [comment]
@shahzeb1 Thank you so much for the makeover of the site. Looks cleaner now. 

I'll merge it.

**Comment by amitness** [comment]
@shahzeb1 You might be interested in this [issue](https://github.com/studenton/shuffle/issues/2) as well.  I'll look forward to the PR.

**Pull request merged**
