### PR TITLE
Forward back buttons

### PR DESCRIPTION
**Pull request by thenorthstarblues**
Hello! I created forward and back buttons that allow users to move through the playlist that is randomly selected when the page loads. Please let me know what you think; I look forward to your feedback!

### CODE REVIEW

**Comment by amitness** [comment]
Tried it locally. Looks good. 

I think placing the back and forward buttons to the left and right side of the video will be better. What do you think?

**Comment by thenorthstarblues** [comment]
I was going to ask you about that actually! I like that idea. How do we feel about the color of the buttons? Let me know if you think of any other design changes that might look better. Thanks!

**Comment by amitness** [comment]
The color of the buttons you've chosen feels consistent with overall site design :+1: .

**Comment by amitness** [comment]
Thanks for the contribution, @thenorthstarblues .

**Pull request merged**
